### ISSUE TITLE
Absolute paths not working

### ISSUE THREAD

**Issue by nebbishhacker** [Hypercubed/frontman#1]
If I pass an absolute path in one of the arguments to frontman, (eg `"C:\Users\ben\wobsite\src\documents\posts\new.html.md"`) it does not work. This applies to the source file path, the -t argument, and the -o argument.

I've managed to get it to work (for both absolute and relative paths) on my system by directly modifying frontman\bin\frontman to replace every instance of `path.join(process.cwd(), filename)` or similar with just `filename`.

Absolute paths are handy in my case, since they allow the filepaths to be filled using environment variables when I execute the command through notepad++, making publishing a post I'm editing just a couple clicks :smiley:

Other than that, this is very useful!

**Comment by Hypercubed** [comment]
Sorry I never took a look at this.  This is very old now.  Please reopen if you still need this.
